/* HELLGATE: an original one-map classic FPS prototype. */
const W=640,H=400,VH=320,FOV=Math.PI/3,MAX=18;
const c=document.querySelector('#screen'),g=c.getContext('2d');g.imageSmoothingEnabled=false;
const ui={menu:document.querySelector('#menu'),pause:document.querySelector('#pause'),end:document.querySelector('#end'),hint:document.querySelector('#hint'),instructions:document.querySelector('#instructions')};
const map=[
'###################',
'#S....#.....#....E#',
'#.###.#.###.#.###.#',
'#...#.#...#.#...#.#',
'###.#.###.#.###.#.#',
'#...#.....#.#...#.#',
'#.#####.#.#.#.#.#.#',
'#.....#.#...#.#...#',
'#.###.#.#####.###.#',
'#.#...#....D....#.#',
'#.#.#####.#####.#.#',
'#.#.....M.#...#.#.#',
'#.#####.###.#.#.#.#',
'#.....#...M.#...#.#',
'#.###.#####.#####.#',
'#...#......#......#',
'###################'];
const keys=new Set();let mode='menu',locked=false,last=0,flash=0,message='FIND THE EXIT',messageT=2;
let player,enemies,doors,pickups,shots,kills,weapon,art={ready:false};
const weapons=[{name:'PISTOL',ammo:'bullets',cost:1,damage:18,delay:.26,spread:.025},{name:'SHOTGUN',ammo:'shells',cost:1,damage:8,delay:.62,spread:.13,pellets:7},{name:'PLASMA',ammo:'cells',cost:1,damage:24,delay:.14,spread:.04}];
function img(path){return new Promise((ok,no)=>{let i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=path})}
function crop(im,x,y,w,h,key=true){let o=document.createElement('canvas');o.width=w;o.height=h;let q=o.getContext('2d',{willReadFrequently:true});q.drawImage(im,x,y,w,h,0,0,w,h);if(key){let d=q.getImageData(0,0,w,h);for(let n=0;n<d.data.length;n+=4){let r=d.data[n],gr=d.data[n+1],b=d.data[n+2];if((gr>145&&b>145&&r<90)||(b>170&&r<90&&gr<150))d.data[n+3]=0}q.putImageData(d,0,0)}return o}
async function loadArt(){try{let [w,e,s,f]=await Promise.all([img('../assets/doom/MS-DOS - DOOM _ DOOM II - Miscellaneous - Weapons.png'),img('../assets/doom/MS-DOS - DOOM _ DOOM II - Enemies - Lost Soul.png'),img('../assets/doom/MS-DOS - DOOM _ DOOM II - Miscellaneous - Skies.png'),img('../assets/doom/MS-DOS - DOOM _ DOOM II - Miscellaneous - Doom Guy _ Unnamed Marine Face HUD.png')]);art.weapon=crop(w,940,345,230,130);art.enemy=crop(e,40,30,58,84);art.sky=crop(s,260,0,258,130,false);art.face=crop(f,8,12,145,354,false);art.ready=true}catch(e){console.warn('sprite assets unavailable',e)}}loadArt();
function reset(){player={x:1.5,y:1.5,a:0,hp:100,armor:0,ammo:{bullets:60,shells:18,cells:35},cd:0,hurt:0,bob:0};enemies=[];doors=[];pickups=[];shots=[];kills=0;weapon=0;map.forEach((row,y)=>[...row].forEach((t,x)=>{if(t==='S'){player.x=x+.5;player.y=y+.5}if(t==='M')enemies.push({x:x+.5,y:y+.5,hp:65,cd:1.2,hit:0});if(t==='D')doors.push({x,y,open:0});if(t==='E')pickups.push({x:x+.5,y:y+.5,type:'exit'});}));[[3.5,5.5,'med'],[8.5,3.5,'shells'],[15.5,6.5,'cells'],[15.5,14.5,'armor'],[8.5,13.5,'bullets']].forEach(([x,y,type])=>pickups.push({x,y,type}));message='FIND THE EXIT';messageT=2}
function cell(x,y){return map[Math.floor(y)]?.[Math.floor(x)]||'#'}function door(x,y){return doors.find(d=>d.x===Math.floor(x)&&d.y===Math.floor(y))}function blocked(x,y){let t=cell(x,y);return t==='#'||(t==='D'&&(!door(x,y)||door(x,y).open<.7))}function move(o,x,y,r=.2){if(!blocked(x+r,o.y)&&!blocked(x-r,o.y)&&!blocked(x,o.y+r)&&!blocked(x,o.y-r))o.x=x;if(!blocked(o.x,y+r)&&!blocked(o.x,y-r)&&!blocked(o.x+r,y)&&!blocked(o.x-r,y))o.y=y}
function ray(x,y,a,limit=MAX){let cs=Math.cos(a),sn=Math.sin(a);for(let d=.02;d<limit;d+=.018){let t=cell(x+cs*d,y+sn*d);if(t==='#'||(t==='D'&&door(x+cs*d,y+sn*d)?.open<.7))return{d,t,x:x+cs*d,y:y+sn*d}}return{d:limit,t:null}}
function los(a,b){let d=Math.hypot(a.x-b.x,a.y-b.y),r=ray(a.x,a.y,Math.atan2(b.y-a.y,b.x-a.x),d);return r.d>=d-.05}function angleDiff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
function say(s,t=1.3){message=s;messageT=t}
function use(){let d=door(player.x+Math.cos(player.a)*1.15,player.y+Math.sin(player.a)*1.15);if(d){d.opening=true;say('DOOR OPENING')}else say('NOTHING TO USE')}
function fire(){let w=weapons[weapon];if(player.cd>0)return;if(player.ammo[w.ammo]<w.cost){say('OUT OF AMMO');return}player.ammo[w.ammo]-=w.cost;player.cd=w.delay;flash=.08;let did=false;for(let i=0;i<(w.pellets||1);i++){let a=player.a+(Math.random()-.5)*w.spread,r=ray(player.x,player.y,a,10),near=null,nearD=r.d;enemies.forEach(e=>{let d=Math.hypot(e.x-player.x,e.y-player.y),ad=Math.abs(angleDiff(Math.atan2(e.y-player.y,e.x-player.x),a));if(e.hp>0&&d<nearD&&ad<Math.atan2(.28,d)&&los(player,e)){near=e;nearD=d}});if(near){near.hp-=w.damage*(.8+Math.random()*.4);near.hit=.14;did=true}}enemies=enemies.filter(e=>{if(e.hp>0)return true;kills++;say('DEMON DESTROYED');return false});if(!did)say(w.name+' FIRED',.35)}
function hurt(n){let shield=Math.min(player.armor,n*.5);player.armor-=shield;player.hp-=n-shield;player.hurt=.2;if(player.hp<=0){player.hp=0;finish(false)}}
function update(dt){if(mode!=='play')return;player.cd=Math.max(0,player.cd-dt);player.hurt=Math.max(0,player.hurt-dt);flash=Math.max(0,flash-dt);messageT-=dt;let speed=keys.has('ShiftLeft')?4.2:2.8,dx=0,dy=0;if(keys.has('KeyW')){dx+=Math.cos(player.a)*speed*dt;dy+=Math.sin(player.a)*speed*dt}if(keys.has('KeyS')){dx-=Math.cos(player.a)*speed*dt;dy-=Math.sin(player.a)*speed*dt}if(keys.has('KeyA')){dx+=Math.cos(player.a-Math.PI/2)*speed*dt;dy+=Math.sin(player.a-Math.PI/2)*speed*dt}if(keys.has('KeyD')){dx+=Math.cos(player.a+Math.PI/2)*speed*dt;dy+=Math.sin(player.a+Math.PI/2)*speed*dt}if(keys.has('ArrowLeft'))player.a-=2.5*dt;if(keys.has('ArrowRight'))player.a+=2.5*dt;move(player,player.x+dx,player.y+dy);player.a=(player.a+Math.PI*2)%(Math.PI*2);player.bob+=(Math.abs(dx)+Math.abs(dy))*12;
doors.forEach(d=>{if(d.opening)d.open=Math.min(1,d.open+dt*1.2);else if(d.open>0&&Math.hypot(player.x-d.x-.5,player.y-d.y-.5)>1.4)d.open=Math.max(0,d.open-dt*.25)});
enemies.forEach(e=>{e.cd-=dt;e.hit=Math.max(0,e.hit-dt);let d=Math.hypot(e.x-player.x,e.y-player.y);if(d<9&&los(e,player)){if(d>1.35){let a=Math.atan2(player.y-e.y,player.x-e.x);move(e,e.x+Math.cos(a)*dt*.9,e.y+Math.sin(a)*dt*.9,.22)}if(d<7&&e.cd<=0){e.cd=1+Math.random()*.6;shots.push({x:e.x,y:e.y,vx:(player.x-e.x)/d*4,vy:(player.y-e.y)/d*4,t:2})}}});shots=shots.filter(s=>{s.t-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.t<0||blocked(s.x,s.y))return false;if(Math.hypot(s.x-player.x,s.y-player.y)<.27){hurt(8+Math.random()*7);return false}return true});pickups=pickups.filter(p=>{if(Math.hypot(p.x-player.x,p.y-player.y)>.42)return true;if(p.type==='exit'){finish(true);return false}if(p.type==='med'){player.hp=Math.min(100,player.hp+30);say('MEDIKIT +30')}if(p.type==='armor'){player.armor=Math.min(100,player.armor+40);say('ARMOR +40')}if(p.type==='bullets'){player.ammo.bullets+=25;say('BULLETS +25')}if(p.type==='shells'){player.ammo.shells+=8;say('SHELLS +8')}if(p.type==='cells'){player.ammo.cells+=20;say('CELLS +20')}return false})}
function shade(hex,n){let q=parseInt(hex.slice(1),16),r=(q>>16)*n,gr=((q>>8)&255)*n,b=(q&255)*n;return`rgb(${r|0},${gr|0},${b|0})`}
function draw(){g.clearRect(0,0,W,H);if(art.ready){let offset=-(player?player.a/(Math.PI*2)*260:0)%260;g.drawImage(art.sky,offset,0,260,VH/2);g.drawImage(art.sky,offset+260,0,260,VH/2);g.drawImage(art.sky,offset+520,0,260,VH/2)}else{g.fillStyle='#56120e';g.fillRect(0,0,W,VH/2)}g.fillStyle='#211810';g.fillRect(0,VH/2,W,VH/2);if(!player)return;let depth=new Float32Array(W);for(let x=0;x<W;x++){let a=player.a-FOV/2+x/W*FOV,r=ray(player.x,player.y,a),d=r.d*Math.cos(a-player.a);depth[x]=d;let h=Math.min(VH,VH/d*.75),top=(VH-h)/2,col=r.t==='D'?'#a44222':'#6e4d42';g.fillStyle=shade(col,Math.max(.16,1-d/MAX));g.fillRect(x,top,1,h)}drawSprites(depth);drawHud();if(player.hurt>0){g.fillStyle=`rgba(220,0,0,${player.hurt*.35})`;g.fillRect(0,0,W,H)}}
function project(x,y){let dx=x-player.x,dy=y-player.y,d=Math.hypot(dx,dy),a=angleDiff(Math.atan2(dy,dx),player.a);if(Math.abs(a)>FOV*.65)return null;return{x:W/2+a/FOV*W,y:VH/2,d}}
function sprite(im,p,scale,depth,hit=false){let s=scale/depth,qx=p.x-s/2,qy=p.y-s*.63;for(let x=Math.max(0,qx|0);x<Math.min(W,(qx+s)|0);x++)if(depth<depthBuf[x]){g.save();if(hit)g.globalCompositeOperation='screen';g.drawImage(im,x-qx,0,1,im.height,x,qy,1,s*.9);g.restore()}}
let depthBuf;function drawSprites(depth){depthBuf=depth;let list=[];enemies.forEach(e=>list.push({type:'enemy',o:e}));shots.forEach(s=>list.push({type:'shot',o:s}));pickups.forEach(p=>list.push({type:'pickup',o:p}));list.sort((a,b)=>Math.hypot(b.o.x-player.x,b.o.y-player.y)-Math.hypot(a.o.x-player.x,a.o.y-player.y));list.forEach(v=>{let p=project(v.o.x,v.o.y);if(!p)return;if(v.type==='enemy'&&art.ready)sprite(art.enemy,p,190,p.d,v.o.hit>0);else{let color=v.type==='shot'?'#ff7a1c':v.o.type==='exit'?'#61ff9d':v.o.type==='med'?'#ee3b33':'#ffd057';let z=90/p.d;g.fillStyle=color;g.fillRect(p.x-z/2,p.y-z/2,z,z)}})}
function drawHud(){g.fillStyle='#191919';g.fillRect(0,VH,W,H-VH);g.strokeStyle='#9f9f8c';g.strokeRect(1,VH+1,W-2,H-VH-2);g.fillStyle='#754d35';g.fillRect(4,VH+4,150,72);g.fillStyle='#101010';g.fillRect(158,VH+4,324,72);g.fillRect(486,VH+4,150,72);let w=weapons[weapon],bob=Math.sin(player.bob)*3;if(art.ready)g.drawImage(art.weapon,W/2-130,VH-38+bob,260,147);else{g.fillStyle='#555';g.fillRect(W/2-32,VH-34,64,70)}if(flash>0){g.fillStyle='rgba(255,230,150,.5)';g.fillRect(W/2-16,VH-110,32,60)}g.fillStyle='#f1d28e';g.font='bold 15px monospace';g.fillText('AMMO',12,VH+23);g.fillText(String(player.ammo[w.ammo]).padStart(3,'0'),12,VH+49);g.fillText('HEALTH',170,VH+23);g.fillStyle=player.hp<30?'#f03528':'#f1d28e';g.font='bold 28px monospace';g.fillText(String(player.hp|0).padStart(3,'0')+'%',170,VH+57);g.fillStyle='#f1d28e';g.font='bold 15px monospace';g.fillText('ARMOR',395,VH+23);g.fillText(String(player.armor|0).padStart(3,'0')+'%',395,VH+49);g.fillStyle='#f1d28e';g.fillText('WEAPON '+(weapon+1),497,VH+23);g.fillStyle='#ffb13c';g.font='bold 13px monospace';g.fillText(w.name,497,VH+50);if(messageT>0){g.fillStyle='#ffca52';g.font='bold 13px monospace';g.textAlign='center';g.fillText(message,W/2,20);g.textAlign='left'}}
function finish(win){mode='end';document.exitPointerLock?.();ui.end.classList.remove('hidden');document.querySelector('#end-kicker').textContent=win?'MISSION SUCCESS':'MARINE DOWN';document.querySelector('#end-title').textContent=win?'SECTOR CLEARED':'YOU DIED';document.querySelector('#end-copy').textContent=win?`YOU CLEARED THE FACILITY. ${kills} DEMONS DESTROYED.`:`${kills} DEMONS DESTROYED. RELOAD AND TRY AGAIN.`}
function play(){reset();mode='play';ui.menu.classList.add('hidden');ui.pause.classList.add('hidden');ui.end.classList.add('hidden');c.requestPointerLock?.();ui.hint.classList.add('visible');setTimeout(()=>ui.hint.classList.remove('visible'),1800)}function pause(){if(mode!=='play')return;mode='pause';document.exitPointerLock?.();ui.pause.classList.remove('hidden')}function loop(t){let dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
document.querySelector('#start').onclick=play;document.querySelector('#resume').onclick=()=>{mode='play';ui.pause.classList.add('hidden');c.requestPointerLock?.()};document.querySelector('#quit').onclick=()=>{mode='menu';ui.pause.classList.add('hidden');ui.menu.classList.remove('hidden')};document.querySelector('#again').onclick=play;document.querySelector('#end-menu').onclick=()=>{ui.end.classList.add('hidden');ui.menu.classList.remove('hidden');mode='menu'};document.querySelector('#how').onclick=()=>ui.instructions.classList.toggle('hidden');
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Escape')pause();if(mode==='play'&&e.code==='KeyE')use();if(mode==='play'&&e.code==='Space')fire();if(mode==='play'&&/^Digit[1-3]$/.test(e.code)){weapon=+e.code.at(-1)-1;say(weapons[weapon].name+' READY')}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousemove',e=>{if(locked&&mode==='play')player.a+=e.movementX*.0023});addEventListener('mousedown',e=>{if(e.button===0&&mode==='play'){if(locked)fire();else c.requestPointerLock?.()}});document.addEventListener('pointerlockchange',()=>{let was=locked;locked=document.pointerLockElement===c;if(was&&!locked&&mode==='play')pause()});
reset();requestAnimationFrame(loop);
